### ISSUE TITLE
INFOGRAFIA_MARIA JOSE LOPEZ LEYVA

### ISSUE THREAD

**Issue by MariaJose-10** [SistemasTecTlaxiaco/actividad-1-infografia-MariaJose-10#2]
[INFOGRAFIA_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-MariaJose-10/files/9424510/INFOGRAFIA_MARIA.JOSE.LOPEZ.LEYVA.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
